### ISSUE TITLE
Nothing Happens When Enabled: java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by eblocha** [ScreteMonge/3D-Weather#20]
Nothing happens at all when the plugin is loaded and enabled. The client logs only show this message:

```
2023-06-28 22:16:21 AKDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Unknown Source)
	at com.weather3d.CyclesPlugin.renderWeather(CyclesPlugin.java:704)
	at com.weather3d.CyclesPlugin.handleWeatherChanges(CyclesPlugin.java:659)
	at com.weather3d.CyclesPlugin.onGameTick(CyclesPlugin.java:204)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:209)
	at client.pa(client.java:52780)
	at client.bn(client.java)
	at ba.al(ba.java:382)
	at ba.run(ba.java:361)
	at java.base/java.lang.Thread.run(Unknown Source)
```

This message will only occur once after starting the client, uninstalling and reinstalling does not cause more messages.

**Comment by ScreteMonge** [comment]
Sorry for the delay in response. Thank you for letting me know.

This update was reverted a while back. It's being re-added with this particular bug fixed.
